/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Visuable for You Table Tennis API
 * OpenAPI spec version: 0.1.0
 */
export interface BodyLoginAuthLoginPost {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
}

export interface BodyUploadVideoVideosPost {
  title: string;
  file: Blob;
}

/**
 * 切り抜き動画レスポンス（クリップはMLサービスが生成するためCreateスキーマは不要）
 */
export interface ClipResponse {
  id: string;
  video_id: string;
  job_id: string;
  start_time: number;
  end_time: number;
  storage_path: string;
  created_at: string;
}

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type JobStatus = typeof JobStatus[keyof typeof JobStatus];


export const JobStatus = {
  queued: 'queued',
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

/**
 * ジョブ情報レスポンス（ジョブはシステム側で作成するためCreateスキーマは不要）
 */
export interface JobResponse {
  id: string;
  video_id: string;
  status: JobStatus;
  started_at: string | null;
  completed_at: string | null;
  error_message: string | null;
  created_at: string;
}

/**
 * JWTトークンレスポンス
 */
export interface TokenResponse {
  access_token: string;
  token_type?: string;
}

/**
 * ユーザー登録リクエスト
 */
export interface UserCreate {
  email: string;
  password: string;
  display_name: string;
}

/**
 * ユーザー情報レスポンス（password_hash は返さない）
 */
export interface UserResponse {
  id: string;
  email: string;
  display_name: string;
  email_verified: boolean;
  created_at: string;
}

export type VideoStatus = typeof VideoStatus[keyof typeof VideoStatus];


export const VideoStatus = {
  uploaded: 'uploaded',
  queued: 'queued',
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

/**
 * 動画情報レスポンス
 */
export interface VideoResponse {
  id: string;
  user_id: string;
  title: string;
  storage_path: string;
  duration: number | null;
  status: VideoStatus;
  created_at: string;
  updated_at: string;
}

export type HealthHealthGet200 = { [key: string]: unknown };

/**
 * ログイン（JWTトークンを発行する）
 * @summary Login
 */
export type loginAuthLoginPostResponse200 = {
  data: TokenResponse
  status: 200
}

export type loginAuthLoginPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type loginAuthLoginPostResponseSuccess = (loginAuthLoginPostResponse200) & {
  headers: Headers;
};
export type loginAuthLoginPostResponseError = (loginAuthLoginPostResponse422) & {
  headers: Headers;
};

export type loginAuthLoginPostResponse = (loginAuthLoginPostResponseSuccess | loginAuthLoginPostResponseError)

export const getLoginAuthLoginPostUrl = () => {


  

  return `/api/auth/login`
}

export const loginAuthLoginPost = async (bodyLoginAuthLoginPost: BodyLoginAuthLoginPost, options?: RequestInit): Promise<loginAuthLoginPostResponse> => {
    const formUrlEncoded = new URLSearchParams();
if(bodyLoginAuthLoginPost.grant_type !== undefined && bodyLoginAuthLoginPost.grant_type !== null) {
 formUrlEncoded.append(`grant_type`, bodyLoginAuthLoginPost.grant_type);
 }
formUrlEncoded.append(`username`, bodyLoginAuthLoginPost.username);
formUrlEncoded.append(`password`, bodyLoginAuthLoginPost.password);
if(bodyLoginAuthLoginPost.scope !== undefined) {
 formUrlEncoded.append(`scope`, bodyLoginAuthLoginPost.scope);
 }
if(bodyLoginAuthLoginPost.client_id !== undefined && bodyLoginAuthLoginPost.client_id !== null) {
 formUrlEncoded.append(`client_id`, bodyLoginAuthLoginPost.client_id);
 }
if(bodyLoginAuthLoginPost.client_secret !== undefined && bodyLoginAuthLoginPost.client_secret !== null) {
 formUrlEncoded.append(`client_secret`, bodyLoginAuthLoginPost.client_secret);
 }

  const res = await fetch(getLoginAuthLoginPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body: 
      formUrlEncoded,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: loginAuthLoginPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as loginAuthLoginPostResponse
}
  


/**
 * ユーザー登録
 * @summary Register
 */
export type registerUsersPostResponse201 = {
  data: UserResponse
  status: 201
}

export type registerUsersPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type registerUsersPostResponseSuccess = (registerUsersPostResponse201) & {
  headers: Headers;
};
export type registerUsersPostResponseError = (registerUsersPostResponse422) & {
  headers: Headers;
};

export type registerUsersPostResponse = (registerUsersPostResponseSuccess | registerUsersPostResponseError)

export const getRegisterUsersPostUrl = () => {


  

  return `/api/users`
}

export const registerUsersPost = async (userCreate: UserCreate, options?: RequestInit): Promise<registerUsersPostResponse> => {
  
  const res = await fetch(getRegisterUsersPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userCreate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: registerUsersPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as registerUsersPostResponse
}
  


/**
 * ログイン中のユーザー情報を取得
 * @summary Get Me
 */
export type getMeUsersMeGetResponse200 = {
  data: UserResponse
  status: 200
}

export type getMeUsersMeGetResponseSuccess = (getMeUsersMeGetResponse200) & {
  headers: Headers;
};
;

export type getMeUsersMeGetResponse = (getMeUsersMeGetResponseSuccess)

export const getGetMeUsersMeGetUrl = () => {


  

  return `/api/users/me`
}

export const getMeUsersMeGet = async ( options?: RequestInit): Promise<getMeUsersMeGetResponse> => {
  
  const res = await fetch(getGetMeUsersMeGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMeUsersMeGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMeUsersMeGetResponse
}
  


/**
 * ログインユーザーの動画一覧取得
 * @summary List Videos
 */
export type listVideosVideosGetResponse200 = {
  data: VideoResponse[]
  status: 200
}

export type listVideosVideosGetResponseSuccess = (listVideosVideosGetResponse200) & {
  headers: Headers;
};
;

export type listVideosVideosGetResponse = (listVideosVideosGetResponseSuccess)

export const getListVideosVideosGetUrl = () => {


  

  return `/api/videos`
}

export const listVideosVideosGet = async ( options?: RequestInit): Promise<listVideosVideosGetResponse> => {
  
  const res = await fetch(getListVideosVideosGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listVideosVideosGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listVideosVideosGetResponse
}
  


/**
 * 動画アップロード
 * @summary Upload Video
 */
export type uploadVideoVideosPostResponse201 = {
  data: VideoResponse
  status: 201
}

export type uploadVideoVideosPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type uploadVideoVideosPostResponseSuccess = (uploadVideoVideosPostResponse201) & {
  headers: Headers;
};
export type uploadVideoVideosPostResponseError = (uploadVideoVideosPostResponse422) & {
  headers: Headers;
};

export type uploadVideoVideosPostResponse = (uploadVideoVideosPostResponseSuccess | uploadVideoVideosPostResponseError)

export const getUploadVideoVideosPostUrl = () => {


  

  return `/api/videos`
}

export const uploadVideoVideosPost = async (bodyUploadVideoVideosPost: BodyUploadVideoVideosPost, options?: RequestInit): Promise<uploadVideoVideosPostResponse> => {
    const formData = new FormData();
formData.append(`title`, bodyUploadVideoVideosPost.title);
formData.append(`file`, bodyUploadVideoVideosPost.file);

  const res = await fetch(getUploadVideoVideosPostUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: uploadVideoVideosPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as uploadVideoVideosPostResponse
}
  


/**
 * 動画詳細取得
 * @summary Get Video
 */
export type getVideoVideosVideoIdGetResponse200 = {
  data: VideoResponse
  status: 200
}

export type getVideoVideosVideoIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getVideoVideosVideoIdGetResponseSuccess = (getVideoVideosVideoIdGetResponse200) & {
  headers: Headers;
};
export type getVideoVideosVideoIdGetResponseError = (getVideoVideosVideoIdGetResponse422) & {
  headers: Headers;
};

export type getVideoVideosVideoIdGetResponse = (getVideoVideosVideoIdGetResponseSuccess | getVideoVideosVideoIdGetResponseError)

export const getGetVideoVideosVideoIdGetUrl = (videoId: string,) => {


  

  return `/api/videos/${videoId}`
}

export const getVideoVideosVideoIdGet = async (videoId: string, options?: RequestInit): Promise<getVideoVideosVideoIdGetResponse> => {
  
  const res = await fetch(getGetVideoVideosVideoIdGetUrl(videoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getVideoVideosVideoIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getVideoVideosVideoIdGetResponse
}
  


/**
 * ジョブ詳細取得
 * @summary Get Job
 */
export type getJobJobsJobIdGetResponse200 = {
  data: JobResponse
  status: 200
}

export type getJobJobsJobIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getJobJobsJobIdGetResponseSuccess = (getJobJobsJobIdGetResponse200) & {
  headers: Headers;
};
export type getJobJobsJobIdGetResponseError = (getJobJobsJobIdGetResponse422) & {
  headers: Headers;
};

export type getJobJobsJobIdGetResponse = (getJobJobsJobIdGetResponseSuccess | getJobJobsJobIdGetResponseError)

export const getGetJobJobsJobIdGetUrl = (jobId: string,) => {


  

  return `/api/jobs/${jobId}`
}

export const getJobJobsJobIdGet = async (jobId: string, options?: RequestInit): Promise<getJobJobsJobIdGetResponse> => {
  
  const res = await fetch(getGetJobJobsJobIdGetUrl(jobId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getJobJobsJobIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getJobJobsJobIdGetResponse
}
  


/**
 * 動画に紐づくジョブ一覧取得
 * @summary List Jobs By Video
 */
export type listJobsByVideoVideosVideoIdJobsGetResponse200 = {
  data: JobResponse[]
  status: 200
}

export type listJobsByVideoVideosVideoIdJobsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listJobsByVideoVideosVideoIdJobsGetResponseSuccess = (listJobsByVideoVideosVideoIdJobsGetResponse200) & {
  headers: Headers;
};
export type listJobsByVideoVideosVideoIdJobsGetResponseError = (listJobsByVideoVideosVideoIdJobsGetResponse422) & {
  headers: Headers;
};

export type listJobsByVideoVideosVideoIdJobsGetResponse = (listJobsByVideoVideosVideoIdJobsGetResponseSuccess | listJobsByVideoVideosVideoIdJobsGetResponseError)

export const getListJobsByVideoVideosVideoIdJobsGetUrl = (videoId: string,) => {


  

  return `/api/videos/${videoId}/jobs`
}

export const listJobsByVideoVideosVideoIdJobsGet = async (videoId: string, options?: RequestInit): Promise<listJobsByVideoVideosVideoIdJobsGetResponse> => {
  
  const res = await fetch(getListJobsByVideoVideosVideoIdJobsGetUrl(videoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listJobsByVideoVideosVideoIdJobsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listJobsByVideoVideosVideoIdJobsGetResponse
}
  


/**
 * 動画に紐づく切り抜き一覧取得
 * @summary List Clips By Video
 */
export type listClipsByVideoVideosVideoIdClipsGetResponse200 = {
  data: ClipResponse[]
  status: 200
}

export type listClipsByVideoVideosVideoIdClipsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listClipsByVideoVideosVideoIdClipsGetResponseSuccess = (listClipsByVideoVideosVideoIdClipsGetResponse200) & {
  headers: Headers;
};
export type listClipsByVideoVideosVideoIdClipsGetResponseError = (listClipsByVideoVideosVideoIdClipsGetResponse422) & {
  headers: Headers;
};

export type listClipsByVideoVideosVideoIdClipsGetResponse = (listClipsByVideoVideosVideoIdClipsGetResponseSuccess | listClipsByVideoVideosVideoIdClipsGetResponseError)

export const getListClipsByVideoVideosVideoIdClipsGetUrl = (videoId: string,) => {


  

  return `/api/videos/${videoId}/clips`
}

export const listClipsByVideoVideosVideoIdClipsGet = async (videoId: string, options?: RequestInit): Promise<listClipsByVideoVideosVideoIdClipsGetResponse> => {
  
  const res = await fetch(getListClipsByVideoVideosVideoIdClipsGetUrl(videoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listClipsByVideoVideosVideoIdClipsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listClipsByVideoVideosVideoIdClipsGetResponse
}
  


/**
 * @summary Health
 */
export type healthHealthGetResponse200 = {
  data: HealthHealthGet200
  status: 200
}

export type healthHealthGetResponseSuccess = (healthHealthGetResponse200) & {
  headers: Headers;
};
;

export type healthHealthGetResponse = (healthHealthGetResponseSuccess)

export const getHealthHealthGetUrl = () => {


  

  return `/api/health`
}

export const healthHealthGet = async ( options?: RequestInit): Promise<healthHealthGetResponse> => {
  
  const res = await fetch(getHealthHealthGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: healthHealthGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as healthHealthGetResponse
}
