/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Visuable for You Table Tennis API
 * OpenAPI spec version: 0.1.0
 */
export interface BodyChunkUploadVideosUploadUploadIdChunkPost {
  file: Blob;
}

export interface BodyLoginAuthLoginPost {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
}

export interface BodyUploadVideoVideosPost {
  title: string;
  file: Blob;
}

/**
 * チャンクアップロード初期化リクエスト

total_bytes はサイズ上限を「1 バイトも受け取る前に」判定するために受け取る。
自己申告なので信用はせず、実際の受信量は save_chunk 側でも累積検査する。
 */
export interface ChunkUploadInitRequest {
  title: string;
  filename: string;
  total_chunks: number;
  total_bytes: number;
}

/**
 * チャンクアップロード初期化レスポンス
 */
export interface ChunkUploadInitResponse {
  upload_id: string;
}

/**
 * MLサービスが返す1シーンの区間（秒）
 */
export interface ClipData {
  start_time: number;
  end_time: number;
}

/**
 * ユーザー編集で送られる 1 区間。連結順は配列内の並び順で決まる。
 */
export interface ClipInput {
  /** @minimum 0 */
  start_time: number;
  /** @exclusiveMinimum 0 */
  end_time: number;
}

/**
 * 切り抜き区間レスポンス
 */
export interface ClipResponse {
  id: string;
  video_id: string;
  job_id: string;
  start_time: number;
  end_time: number;
  sort_order: number;
  storage_path: string;
  created_at: string;
}

/**
 * 切り抜き一括置換リクエスト（PUT /videos/{id}/clips）。

送られた配列で動画の切り抜きをまるごと置き換える。新規・編集・削除・
並べ替えをこの 1 リクエストで表現する。
 */
export interface ClipsReplaceRequest {
  /** @maxItems 200 */
  clips: ClipInput[];
}

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

/**
 * MLサービスからの処理完了コールバックのリクエストボディ。

job_id はパスパラメータで受け取るためボディには持たない。
 */
export interface JobCompleteRequest {
  clips: ClipData[];
}

/**
 * MLサービスからの処理失敗コールバックのリクエストボディ。

job_id はパスパラメータで受け取るためボディには持たない。
 */
export interface JobFailRequest {
  error: string;
}

export type JobStatus = typeof JobStatus[keyof typeof JobStatus];


export const JobStatus = {
  queued: 'queued',
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

/**
 * ジョブ情報レスポンス（ジョブはシステム側で作成するためCreateスキーマは不要）
 */
export interface JobResponse {
  id: string;
  video_id: string;
  status: JobStatus;
  started_at: string | null;
  completed_at: string | null;
  error_message: string | null;
  retry_count: number;
  next_retry_at: string | null;
  created_at: string;
  updated_at: string;
}

export type StorageMetricsResponseVideosPerUser = {[key: string]: number};

/**
 * R2 / DB のストレージ統計レスポンス
 */
export interface StorageMetricsResponse {
  r2_total_bytes: number;
  r2_object_count: number;
  db_video_count: number;
  videos_per_user: StorageMetricsResponseVideosPerUser;
}

/**
 * JWTトークンレスポンス
 */
export interface TokenResponse {
  access_token: string;
  token_type?: string;
}

/**
 * ユーザー登録リクエスト
 */
export interface UserCreate {
  email: string;
  password: string;
  display_name: string;
}

/**
 * ユーザー情報レスポンス（password_hash は返さない）
 */
export interface UserResponse {
  id: string;
  email: string;
  display_name: string;
  email_verified: boolean;
  created_at: string;
}

/**
 * ユーザー情報更新リクエスト
 */
export interface UserUpdate {
  display_name?: string | null;
  password?: string | null;
}

/**
 * 連結済み動画の取得用レスポンス。

R2 の presigned URL（短命・推測不可）を返し、フロントは <video src> /
ダウンロード href にこの URL を直接セットする。認可はこのエンドポイントで
行い、バイト本体は R2 から直接配信する。

url はインライン再生用、download_url は Content-Disposition: attachment 付きで
ブラウザに保存させる用（クロスオリジン URL では <a download> が無視されるため、
ヘッダ側で attachment を指定しないとモバイルで再生画面が開くだけになる）。
 */
export interface VideoOutputResponse {
  url: string;
  download_url?: string | null;
}

export type VideoStatus = typeof VideoStatus[keyof typeof VideoStatus];


export const VideoStatus = {
  uploaded: 'uploaded',
  queued: 'queued',
  processing: 'processing',
  ready: 'ready',
  completed: 'completed',
  failed: 'failed',
} as const;

/**
 * 動画情報レスポンス
 */
export interface VideoResponse {
  id: string;
  user_id: string;
  title: string;
  storage_path: string;
  output_path: string | null;
  duration: number | null;
  source_duration: number | null;
  status: VideoStatus;
  created_at: string;
  updated_at: string;
  expires_at: string;
  thumbnail_url?: string | null;
}

export type VerifyEmailAuthVerifyEmailGetParams = {
token: string;
};

export type ChunkUploadVideosUploadUploadIdChunkPostParams = {
index: number;
};

export type CompleteJobInternalJobsJobIdCompletePost202 = { [key: string]: unknown };

export type FailJobInternalJobsJobIdFailPost202 = { [key: string]: unknown };

export type HealthHealthGet200 = { [key: string]: unknown };

/**
 * ログイン（JWTトークンを発行する）
 * @summary Login
 */
export type loginAuthLoginPostResponse200 = {
  data: TokenResponse
  status: 200
}

export type loginAuthLoginPostResponse401 = {
  data: void
  status: 401
}

export type loginAuthLoginPostResponse403 = {
  data: void
  status: 403
}

export type loginAuthLoginPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type loginAuthLoginPostResponseSuccess = (loginAuthLoginPostResponse200) & {
  headers: Headers;
};
export type loginAuthLoginPostResponseError = (loginAuthLoginPostResponse401 | loginAuthLoginPostResponse403 | loginAuthLoginPostResponse422) & {
  headers: Headers;
};

export type loginAuthLoginPostResponse = (loginAuthLoginPostResponseSuccess | loginAuthLoginPostResponseError)

export const getLoginAuthLoginPostUrl = () => {


  

  return `/api/auth/login`
}

export const loginAuthLoginPost = async (bodyLoginAuthLoginPost: BodyLoginAuthLoginPost, options?: RequestInit): Promise<loginAuthLoginPostResponse> => {
    const formUrlEncoded = new URLSearchParams();
if(bodyLoginAuthLoginPost.grant_type !== undefined && bodyLoginAuthLoginPost.grant_type !== null) {
 formUrlEncoded.append(`grant_type`, bodyLoginAuthLoginPost.grant_type);
 }
formUrlEncoded.append(`username`, bodyLoginAuthLoginPost.username);
formUrlEncoded.append(`password`, bodyLoginAuthLoginPost.password);
if(bodyLoginAuthLoginPost.scope !== undefined) {
 formUrlEncoded.append(`scope`, bodyLoginAuthLoginPost.scope);
 }
if(bodyLoginAuthLoginPost.client_id !== undefined && bodyLoginAuthLoginPost.client_id !== null) {
 formUrlEncoded.append(`client_id`, bodyLoginAuthLoginPost.client_id);
 }
if(bodyLoginAuthLoginPost.client_secret !== undefined && bodyLoginAuthLoginPost.client_secret !== null) {
 formUrlEncoded.append(`client_secret`, bodyLoginAuthLoginPost.client_secret);
 }

  const res = await fetch(getLoginAuthLoginPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body: 
      formUrlEncoded,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: loginAuthLoginPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as loginAuthLoginPostResponse
}
  


/**
 * @summary Verify Email
 */
export type verifyEmailAuthVerifyEmailGetResponse200 = {
  data: unknown
  status: 200
}

export type verifyEmailAuthVerifyEmailGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type verifyEmailAuthVerifyEmailGetResponseSuccess = (verifyEmailAuthVerifyEmailGetResponse200) & {
  headers: Headers;
};
export type verifyEmailAuthVerifyEmailGetResponseError = (verifyEmailAuthVerifyEmailGetResponse422) & {
  headers: Headers;
};

export type verifyEmailAuthVerifyEmailGetResponse = (verifyEmailAuthVerifyEmailGetResponseSuccess | verifyEmailAuthVerifyEmailGetResponseError)

export const getVerifyEmailAuthVerifyEmailGetUrl = (params: VerifyEmailAuthVerifyEmailGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/auth/verify-email?${stringifiedParams}` : `/api/auth/verify-email`
}

export const verifyEmailAuthVerifyEmailGet = async (params: VerifyEmailAuthVerifyEmailGetParams, options?: RequestInit): Promise<verifyEmailAuthVerifyEmailGetResponse> => {
  
  const res = await fetch(getVerifyEmailAuthVerifyEmailGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: verifyEmailAuthVerifyEmailGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as verifyEmailAuthVerifyEmailGetResponse
}
  


/**
 * ユーザー登録
 * @summary Register
 */
export type registerUsersPostResponse201 = {
  data: UserResponse
  status: 201
}

export type registerUsersPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type registerUsersPostResponseSuccess = (registerUsersPostResponse201) & {
  headers: Headers;
};
export type registerUsersPostResponseError = (registerUsersPostResponse422) & {
  headers: Headers;
};

export type registerUsersPostResponse = (registerUsersPostResponseSuccess | registerUsersPostResponseError)

export const getRegisterUsersPostUrl = () => {


  

  return `/api/users`
}

export const registerUsersPost = async (userCreate: UserCreate, options?: RequestInit): Promise<registerUsersPostResponse> => {
  
  const res = await fetch(getRegisterUsersPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userCreate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: registerUsersPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as registerUsersPostResponse
}
  


/**
 * ログイン中のユーザー情報を取得
 * @summary Get Me
 */
export type getMeUsersMeGetResponse200 = {
  data: UserResponse
  status: 200
}

export type getMeUsersMeGetResponseSuccess = (getMeUsersMeGetResponse200) & {
  headers: Headers;
};
;

export type getMeUsersMeGetResponse = (getMeUsersMeGetResponseSuccess)

export const getGetMeUsersMeGetUrl = () => {


  

  return `/api/users/me`
}

export const getMeUsersMeGet = async ( options?: RequestInit): Promise<getMeUsersMeGetResponse> => {
  
  const res = await fetch(getGetMeUsersMeGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMeUsersMeGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMeUsersMeGetResponse
}
  


/**
 * ユーザー情報を更新
 * @summary Update
 */
export type updateUsersMePatchResponse200 = {
  data: UserResponse
  status: 200
}

export type updateUsersMePatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateUsersMePatchResponseSuccess = (updateUsersMePatchResponse200) & {
  headers: Headers;
};
export type updateUsersMePatchResponseError = (updateUsersMePatchResponse422) & {
  headers: Headers;
};

export type updateUsersMePatchResponse = (updateUsersMePatchResponseSuccess | updateUsersMePatchResponseError)

export const getUpdateUsersMePatchUrl = () => {


  

  return `/api/users/me`
}

export const updateUsersMePatch = async (userUpdate: UserUpdate, options?: RequestInit): Promise<updateUsersMePatchResponse> => {
  
  const res = await fetch(getUpdateUsersMePatchUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userUpdate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateUsersMePatchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateUsersMePatchResponse
}
  


/**
 * ログインユーザーの動画一覧取得
 * @summary List Videos
 */
export type listVideosVideosGetResponse200 = {
  data: VideoResponse[]
  status: 200
}

export type listVideosVideosGetResponseSuccess = (listVideosVideosGetResponse200) & {
  headers: Headers;
};
;

export type listVideosVideosGetResponse = (listVideosVideosGetResponseSuccess)

export const getListVideosVideosGetUrl = () => {


  

  return `/api/videos`
}

export const listVideosVideosGet = async ( options?: RequestInit): Promise<listVideosVideosGetResponse> => {
  
  const res = await fetch(getListVideosVideosGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listVideosVideosGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listVideosVideosGetResponse
}
  


/**
 * 動画アップロード（単一リクエスト）

NOTE: 現在フロントエンドからは未使用。フロントは大容量対応のためチャンク
アップロード（/videos/upload/init|chunk|complete、frontend/src/lib/chunkedUpload.ts）
を使用している。小容量の直アップロード・動作確認・将来用途のために保持している。
自分の current_user.id で作成するため所有者チェックは不要。
 * @summary Upload Video
 */
export type uploadVideoVideosPostResponse201 = {
  data: VideoResponse
  status: 201
}

export type uploadVideoVideosPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type uploadVideoVideosPostResponseSuccess = (uploadVideoVideosPostResponse201) & {
  headers: Headers;
};
export type uploadVideoVideosPostResponseError = (uploadVideoVideosPostResponse422) & {
  headers: Headers;
};

export type uploadVideoVideosPostResponse = (uploadVideoVideosPostResponseSuccess | uploadVideoVideosPostResponseError)

export const getUploadVideoVideosPostUrl = () => {


  

  return `/api/videos`
}

export const uploadVideoVideosPost = async (bodyUploadVideoVideosPost: BodyUploadVideoVideosPost, options?: RequestInit): Promise<uploadVideoVideosPostResponse> => {
    const formData = new FormData();
formData.append(`title`, bodyUploadVideoVideosPost.title);
formData.append(`file`, bodyUploadVideoVideosPost.file);

  const res = await fetch(getUploadVideoVideosPostUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: uploadVideoVideosPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as uploadVideoVideosPostResponse
}
  


/**
 * チャンクアップロード初期化
 * @summary Chunk Upload Init
 */
export type chunkUploadInitVideosUploadInitPostResponse200 = {
  data: ChunkUploadInitResponse
  status: 200
}

export type chunkUploadInitVideosUploadInitPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type chunkUploadInitVideosUploadInitPostResponseSuccess = (chunkUploadInitVideosUploadInitPostResponse200) & {
  headers: Headers;
};
export type chunkUploadInitVideosUploadInitPostResponseError = (chunkUploadInitVideosUploadInitPostResponse422) & {
  headers: Headers;
};

export type chunkUploadInitVideosUploadInitPostResponse = (chunkUploadInitVideosUploadInitPostResponseSuccess | chunkUploadInitVideosUploadInitPostResponseError)

export const getChunkUploadInitVideosUploadInitPostUrl = () => {


  

  return `/api/videos/upload/init`
}

export const chunkUploadInitVideosUploadInitPost = async (chunkUploadInitRequest: ChunkUploadInitRequest, options?: RequestInit): Promise<chunkUploadInitVideosUploadInitPostResponse> => {
  
  const res = await fetch(getChunkUploadInitVideosUploadInitPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      chunkUploadInitRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: chunkUploadInitVideosUploadInitPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as chunkUploadInitVideosUploadInitPostResponse
}
  


/**
 * チャンクデータ受信
 * @summary Chunk Upload
 */
export type chunkUploadVideosUploadUploadIdChunkPostResponse204 = {
  data: void
  status: 204
}

export type chunkUploadVideosUploadUploadIdChunkPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type chunkUploadVideosUploadUploadIdChunkPostResponseSuccess = (chunkUploadVideosUploadUploadIdChunkPostResponse204) & {
  headers: Headers;
};
export type chunkUploadVideosUploadUploadIdChunkPostResponseError = (chunkUploadVideosUploadUploadIdChunkPostResponse422) & {
  headers: Headers;
};

export type chunkUploadVideosUploadUploadIdChunkPostResponse = (chunkUploadVideosUploadUploadIdChunkPostResponseSuccess | chunkUploadVideosUploadUploadIdChunkPostResponseError)

export const getChunkUploadVideosUploadUploadIdChunkPostUrl = (uploadId: string,
    params: ChunkUploadVideosUploadUploadIdChunkPostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/videos/upload/${uploadId}/chunk?${stringifiedParams}` : `/api/videos/upload/${uploadId}/chunk`
}

export const chunkUploadVideosUploadUploadIdChunkPost = async (uploadId: string,
    bodyChunkUploadVideosUploadUploadIdChunkPost: BodyChunkUploadVideosUploadUploadIdChunkPost,
    params: ChunkUploadVideosUploadUploadIdChunkPostParams, options?: RequestInit): Promise<chunkUploadVideosUploadUploadIdChunkPostResponse> => {
    const formData = new FormData();
formData.append(`file`, bodyChunkUploadVideosUploadUploadIdChunkPost.file);

  const res = await fetch(getChunkUploadVideosUploadUploadIdChunkPostUrl(uploadId,params),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: chunkUploadVideosUploadUploadIdChunkPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as chunkUploadVideosUploadUploadIdChunkPostResponse
}
  


/**
 * チャンクアップロード完了・動画結合
 * @summary Chunk Upload Complete
 */
export type chunkUploadCompleteVideosUploadUploadIdCompletePostResponse201 = {
  data: VideoResponse
  status: 201
}

export type chunkUploadCompleteVideosUploadUploadIdCompletePostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type chunkUploadCompleteVideosUploadUploadIdCompletePostResponseSuccess = (chunkUploadCompleteVideosUploadUploadIdCompletePostResponse201) & {
  headers: Headers;
};
export type chunkUploadCompleteVideosUploadUploadIdCompletePostResponseError = (chunkUploadCompleteVideosUploadUploadIdCompletePostResponse422) & {
  headers: Headers;
};

export type chunkUploadCompleteVideosUploadUploadIdCompletePostResponse = (chunkUploadCompleteVideosUploadUploadIdCompletePostResponseSuccess | chunkUploadCompleteVideosUploadUploadIdCompletePostResponseError)

export const getChunkUploadCompleteVideosUploadUploadIdCompletePostUrl = (uploadId: string,) => {


  

  return `/api/videos/upload/${uploadId}/complete`
}

export const chunkUploadCompleteVideosUploadUploadIdCompletePost = async (uploadId: string, options?: RequestInit): Promise<chunkUploadCompleteVideosUploadUploadIdCompletePostResponse> => {
  
  const res = await fetch(getChunkUploadCompleteVideosUploadUploadIdCompletePostUrl(uploadId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: chunkUploadCompleteVideosUploadUploadIdCompletePostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as chunkUploadCompleteVideosUploadUploadIdCompletePostResponse
}
  


/**
 * 動画詳細取得
 * @summary Get Video
 */
export type getVideoVideosVideoIdGetResponse200 = {
  data: VideoResponse
  status: 200
}

export type getVideoVideosVideoIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getVideoVideosVideoIdGetResponseSuccess = (getVideoVideosVideoIdGetResponse200) & {
  headers: Headers;
};
export type getVideoVideosVideoIdGetResponseError = (getVideoVideosVideoIdGetResponse422) & {
  headers: Headers;
};

export type getVideoVideosVideoIdGetResponse = (getVideoVideosVideoIdGetResponseSuccess | getVideoVideosVideoIdGetResponseError)

export const getGetVideoVideosVideoIdGetUrl = (videoId: string,) => {


  

  return `/api/videos/${videoId}`
}

export const getVideoVideosVideoIdGet = async (videoId: string, options?: RequestInit): Promise<getVideoVideosVideoIdGetResponse> => {
  
  const res = await fetch(getGetVideoVideosVideoIdGetUrl(videoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getVideoVideosVideoIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getVideoVideosVideoIdGetResponse
}
  


/**
 * 動画削除
 * @summary Delete Video
 */
export type deleteVideoVideosVideoIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteVideoVideosVideoIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteVideoVideosVideoIdDeleteResponseSuccess = (deleteVideoVideosVideoIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteVideoVideosVideoIdDeleteResponseError = (deleteVideoVideosVideoIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteVideoVideosVideoIdDeleteResponse = (deleteVideoVideosVideoIdDeleteResponseSuccess | deleteVideoVideosVideoIdDeleteResponseError)

export const getDeleteVideoVideosVideoIdDeleteUrl = (videoId: string,) => {


  

  return `/api/videos/${videoId}`
}

export const deleteVideoVideosVideoIdDelete = async (videoId: string, options?: RequestInit): Promise<deleteVideoVideosVideoIdDeleteResponse> => {
  
  const res = await fetch(getDeleteVideoVideosVideoIdDeleteUrl(videoId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteVideoVideosVideoIdDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteVideoVideosVideoIdDeleteResponse
}
  


/**
 * 連結済み動画の presigned URL を返す。

認可（JWT＋所有者）は get_owned_video が担い、バイト本体は払い出した
presigned URL でフロントが R2 から直接取得する。
 * @summary Get Output Video
 */
export type getOutputVideoVideosVideoIdOutputGetResponse200 = {
  data: VideoOutputResponse
  status: 200
}

export type getOutputVideoVideosVideoIdOutputGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getOutputVideoVideosVideoIdOutputGetResponseSuccess = (getOutputVideoVideosVideoIdOutputGetResponse200) & {
  headers: Headers;
};
export type getOutputVideoVideosVideoIdOutputGetResponseError = (getOutputVideoVideosVideoIdOutputGetResponse422) & {
  headers: Headers;
};

export type getOutputVideoVideosVideoIdOutputGetResponse = (getOutputVideoVideosVideoIdOutputGetResponseSuccess | getOutputVideoVideosVideoIdOutputGetResponseError)

export const getGetOutputVideoVideosVideoIdOutputGetUrl = (videoId: string,) => {


  

  return `/api/videos/${videoId}/output`
}

export const getOutputVideoVideosVideoIdOutputGet = async (videoId: string, options?: RequestInit): Promise<getOutputVideoVideosVideoIdOutputGetResponse> => {
  
  const res = await fetch(getGetOutputVideoVideosVideoIdOutputGetUrl(videoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getOutputVideoVideosVideoIdOutputGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getOutputVideoVideosVideoIdOutputGetResponse
}
  


/**
 * 元動画（アップロードされた素材）の presigned URL を返す。

新規切り抜きのトリミング UI で元動画全体を再生するために使う。
認可（JWT＋所有者）は get_owned_video が担い、バイト本体は払い出した
presigned URL でフロントが R2 から直接取得する。
 * @summary Get Source Video
 */
export type getSourceVideoVideosVideoIdSourceGetResponse200 = {
  data: VideoOutputResponse
  status: 200
}

export type getSourceVideoVideosVideoIdSourceGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getSourceVideoVideosVideoIdSourceGetResponseSuccess = (getSourceVideoVideosVideoIdSourceGetResponse200) & {
  headers: Headers;
};
export type getSourceVideoVideosVideoIdSourceGetResponseError = (getSourceVideoVideosVideoIdSourceGetResponse422) & {
  headers: Headers;
};

export type getSourceVideoVideosVideoIdSourceGetResponse = (getSourceVideoVideosVideoIdSourceGetResponseSuccess | getSourceVideoVideosVideoIdSourceGetResponseError)

export const getGetSourceVideoVideosVideoIdSourceGetUrl = (videoId: string,) => {


  

  return `/api/videos/${videoId}/source`
}

export const getSourceVideoVideosVideoIdSourceGet = async (videoId: string, options?: RequestInit): Promise<getSourceVideoVideosVideoIdSourceGetResponse> => {
  
  const res = await fetch(getGetSourceVideoVideosVideoIdSourceGetUrl(videoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getSourceVideoVideosVideoIdSourceGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSourceVideoVideosVideoIdSourceGetResponse
}
  


/**
 * 現在の切り抜き区間から連結動画を書き出す（生成する）。

重い FFmpeg 処理は背景タスクで実行し、video を processing にして即座に返す。
完了すると status が completed になり、GET /videos/{id}/output で取得できる。
 * @summary Export Video
 */
export type exportVideoVideosVideoIdExportPostResponse202 = {
  data: VideoResponse
  status: 202
}

export type exportVideoVideosVideoIdExportPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type exportVideoVideosVideoIdExportPostResponseSuccess = (exportVideoVideosVideoIdExportPostResponse202) & {
  headers: Headers;
};
export type exportVideoVideosVideoIdExportPostResponseError = (exportVideoVideosVideoIdExportPostResponse422) & {
  headers: Headers;
};

export type exportVideoVideosVideoIdExportPostResponse = (exportVideoVideosVideoIdExportPostResponseSuccess | exportVideoVideosVideoIdExportPostResponseError)

export const getExportVideoVideosVideoIdExportPostUrl = (videoId: string,) => {


  

  return `/api/videos/${videoId}/export`
}

export const exportVideoVideosVideoIdExportPost = async (videoId: string, options?: RequestInit): Promise<exportVideoVideosVideoIdExportPostResponse> => {
  
  const res = await fetch(getExportVideoVideosVideoIdExportPostUrl(videoId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: exportVideoVideosVideoIdExportPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as exportVideoVideosVideoIdExportPostResponse
}
  


/**
 * 動画に紐づくジョブ一覧取得
 * @summary List Jobs By Video
 */
export type listJobsByVideoVideosVideoIdJobsGetResponse200 = {
  data: JobResponse[]
  status: 200
}

export type listJobsByVideoVideosVideoIdJobsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listJobsByVideoVideosVideoIdJobsGetResponseSuccess = (listJobsByVideoVideosVideoIdJobsGetResponse200) & {
  headers: Headers;
};
export type listJobsByVideoVideosVideoIdJobsGetResponseError = (listJobsByVideoVideosVideoIdJobsGetResponse422) & {
  headers: Headers;
};

export type listJobsByVideoVideosVideoIdJobsGetResponse = (listJobsByVideoVideosVideoIdJobsGetResponseSuccess | listJobsByVideoVideosVideoIdJobsGetResponseError)

export const getListJobsByVideoVideosVideoIdJobsGetUrl = (videoId: string,) => {


  

  return `/api/videos/${videoId}/jobs`
}

export const listJobsByVideoVideosVideoIdJobsGet = async (videoId: string, options?: RequestInit): Promise<listJobsByVideoVideosVideoIdJobsGetResponse> => {
  
  const res = await fetch(getListJobsByVideoVideosVideoIdJobsGetUrl(videoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listJobsByVideoVideosVideoIdJobsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listJobsByVideoVideosVideoIdJobsGetResponse
}
  


/**
 * 失敗したジョブの手動再実行
 * @summary Retry Job
 */
export type retryJobJobsJobIdRetryPostResponse200 = {
  data: JobResponse
  status: 200
}

export type retryJobJobsJobIdRetryPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type retryJobJobsJobIdRetryPostResponseSuccess = (retryJobJobsJobIdRetryPostResponse200) & {
  headers: Headers;
};
export type retryJobJobsJobIdRetryPostResponseError = (retryJobJobsJobIdRetryPostResponse422) & {
  headers: Headers;
};

export type retryJobJobsJobIdRetryPostResponse = (retryJobJobsJobIdRetryPostResponseSuccess | retryJobJobsJobIdRetryPostResponseError)

export const getRetryJobJobsJobIdRetryPostUrl = (jobId: string,) => {


  

  return `/api/jobs/${jobId}/retry`
}

export const retryJobJobsJobIdRetryPost = async (jobId: string, options?: RequestInit): Promise<retryJobJobsJobIdRetryPostResponse> => {
  
  const res = await fetch(getRetryJobJobsJobIdRetryPostUrl(jobId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: retryJobJobsJobIdRetryPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as retryJobJobsJobIdRetryPostResponse
}
  


/**
 * MLサービスからの処理完了コールバック。

重い結合処理は背景タスクへ委譲し、ML 側の read timeout を回避するため即 202 を返す。
 * @summary Complete Job
 */
export type completeJobInternalJobsJobIdCompletePostResponse202 = {
  data: CompleteJobInternalJobsJobIdCompletePost202
  status: 202
}

export type completeJobInternalJobsJobIdCompletePostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type completeJobInternalJobsJobIdCompletePostResponseSuccess = (completeJobInternalJobsJobIdCompletePostResponse202) & {
  headers: Headers;
};
export type completeJobInternalJobsJobIdCompletePostResponseError = (completeJobInternalJobsJobIdCompletePostResponse422) & {
  headers: Headers;
};

export type completeJobInternalJobsJobIdCompletePostResponse = (completeJobInternalJobsJobIdCompletePostResponseSuccess | completeJobInternalJobsJobIdCompletePostResponseError)

export const getCompleteJobInternalJobsJobIdCompletePostUrl = (jobId: string,) => {


  

  return `/api/internal/jobs/${jobId}/complete`
}

export const completeJobInternalJobsJobIdCompletePost = async (jobId: string,
    jobCompleteRequest: JobCompleteRequest, options?: RequestInit): Promise<completeJobInternalJobsJobIdCompletePostResponse> => {
  
  const res = await fetch(getCompleteJobInternalJobsJobIdCompletePostUrl(jobId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      jobCompleteRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: completeJobInternalJobsJobIdCompletePostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as completeJobInternalJobsJobIdCompletePostResponse
}
  


/**
 * MLサービスからの処理失敗コールバック。

ML 側が自分の失敗を自覚できたときにここへ通知してもらい、job_reaper の
タイムアウト待ち（job_timeout_hours）を経ずに失敗を確定させる。
リトライ判定・通知は complete と同じく背景タスクへ委譲して即 202 を返す。
 * @summary Fail Job
 */
export type failJobInternalJobsJobIdFailPostResponse202 = {
  data: FailJobInternalJobsJobIdFailPost202
  status: 202
}

export type failJobInternalJobsJobIdFailPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type failJobInternalJobsJobIdFailPostResponseSuccess = (failJobInternalJobsJobIdFailPostResponse202) & {
  headers: Headers;
};
export type failJobInternalJobsJobIdFailPostResponseError = (failJobInternalJobsJobIdFailPostResponse422) & {
  headers: Headers;
};

export type failJobInternalJobsJobIdFailPostResponse = (failJobInternalJobsJobIdFailPostResponseSuccess | failJobInternalJobsJobIdFailPostResponseError)

export const getFailJobInternalJobsJobIdFailPostUrl = (jobId: string,) => {


  

  return `/api/internal/jobs/${jobId}/fail`
}

export const failJobInternalJobsJobIdFailPost = async (jobId: string,
    jobFailRequest: JobFailRequest, options?: RequestInit): Promise<failJobInternalJobsJobIdFailPostResponse> => {
  
  const res = await fetch(getFailJobInternalJobsJobIdFailPostUrl(jobId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      jobFailRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: failJobInternalJobsJobIdFailPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as failJobInternalJobsJobIdFailPostResponse
}
  


/**
 * 動画に紐づく切り抜き一覧取得
 * @summary List Clips By Video
 */
export type listClipsByVideoVideosVideoIdClipsGetResponse200 = {
  data: ClipResponse[]
  status: 200
}

export type listClipsByVideoVideosVideoIdClipsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listClipsByVideoVideosVideoIdClipsGetResponseSuccess = (listClipsByVideoVideosVideoIdClipsGetResponse200) & {
  headers: Headers;
};
export type listClipsByVideoVideosVideoIdClipsGetResponseError = (listClipsByVideoVideosVideoIdClipsGetResponse422) & {
  headers: Headers;
};

export type listClipsByVideoVideosVideoIdClipsGetResponse = (listClipsByVideoVideosVideoIdClipsGetResponseSuccess | listClipsByVideoVideosVideoIdClipsGetResponseError)

export const getListClipsByVideoVideosVideoIdClipsGetUrl = (videoId: string,) => {


  

  return `/api/videos/${videoId}/clips`
}

export const listClipsByVideoVideosVideoIdClipsGet = async (videoId: string, options?: RequestInit): Promise<listClipsByVideoVideosVideoIdClipsGetResponse> => {
  
  const res = await fetch(getListClipsByVideoVideosVideoIdClipsGetUrl(videoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listClipsByVideoVideosVideoIdClipsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listClipsByVideoVideosVideoIdClipsGetResponse
}
  


/**
 * 切り抜きを一括置換する（新規・編集・削除・並べ替えをまとめて反映）。

出力動画はこの時点では再生成しない。編集を反映するには
POST /videos/{id}/export で書き出す。
 * @summary Replace Clips By Video
 */
export type replaceClipsByVideoVideosVideoIdClipsPutResponse200 = {
  data: ClipResponse[]
  status: 200
}

export type replaceClipsByVideoVideosVideoIdClipsPutResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type replaceClipsByVideoVideosVideoIdClipsPutResponseSuccess = (replaceClipsByVideoVideosVideoIdClipsPutResponse200) & {
  headers: Headers;
};
export type replaceClipsByVideoVideosVideoIdClipsPutResponseError = (replaceClipsByVideoVideosVideoIdClipsPutResponse422) & {
  headers: Headers;
};

export type replaceClipsByVideoVideosVideoIdClipsPutResponse = (replaceClipsByVideoVideosVideoIdClipsPutResponseSuccess | replaceClipsByVideoVideosVideoIdClipsPutResponseError)

export const getReplaceClipsByVideoVideosVideoIdClipsPutUrl = (videoId: string,) => {


  

  return `/api/videos/${videoId}/clips`
}

export const replaceClipsByVideoVideosVideoIdClipsPut = async (videoId: string,
    clipsReplaceRequest: ClipsReplaceRequest, options?: RequestInit): Promise<replaceClipsByVideoVideosVideoIdClipsPutResponse> => {
  
  const res = await fetch(getReplaceClipsByVideoVideosVideoIdClipsPutUrl(videoId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      clipsReplaceRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: replaceClipsByVideoVideosVideoIdClipsPutResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as replaceClipsByVideoVideosVideoIdClipsPutResponse
}
  


/**
 * R2 使用量・DB レコード数のストレージ統計を返す（管理者用）
 * @summary Get Storage Metrics
 */
export type getStorageMetricsAdminMetricsGetResponse200 = {
  data: StorageMetricsResponse
  status: 200
}

export type getStorageMetricsAdminMetricsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getStorageMetricsAdminMetricsGetResponseSuccess = (getStorageMetricsAdminMetricsGetResponse200) & {
  headers: Headers;
};
export type getStorageMetricsAdminMetricsGetResponseError = (getStorageMetricsAdminMetricsGetResponse422) & {
  headers: Headers;
};

export type getStorageMetricsAdminMetricsGetResponse = (getStorageMetricsAdminMetricsGetResponseSuccess | getStorageMetricsAdminMetricsGetResponseError)

export const getGetStorageMetricsAdminMetricsGetUrl = () => {


  

  return `/api/admin/metrics`
}

export const getStorageMetricsAdminMetricsGet = async ( options?: RequestInit): Promise<getStorageMetricsAdminMetricsGetResponse> => {
  
  const res = await fetch(getGetStorageMetricsAdminMetricsGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getStorageMetricsAdminMetricsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getStorageMetricsAdminMetricsGetResponse
}
  


/**
 * @summary Health
 */
export type healthHealthGetResponse200 = {
  data: HealthHealthGet200
  status: 200
}

export type healthHealthGetResponseSuccess = (healthHealthGetResponse200) & {
  headers: Headers;
};
;

export type healthHealthGetResponse = (healthHealthGetResponseSuccess)

export const getHealthHealthGetUrl = () => {


  

  return `/api/health`
}

export const healthHealthGet = async ( options?: RequestInit): Promise<healthHealthGetResponse> => {
  
  const res = await fetch(getHealthHealthGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: healthHealthGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as healthHealthGetResponse
}
