"""add output_path to videos

Revision ID: d373a4952a37
Revises: 2ba56b9f2a6b
Create Date: 2026-03-03 05:06:14.103381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd373a4952a37'
down_revision: Union[str, None] = '2ba56b9f2a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('output_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'output_path')
    # ### end Alembic commands ###
